GFX:
    jpg_quality: 80
    processor: ImageMagick
    processor_allowTemporaryMasksAsPng: false
    processor_colorspace: sRGB
    processor_effects: 1
    processor_enabled: true
    processor_path: '/usr/bin/'
    processor_path_lzw: '/usr/bin/'