MAIL:
    transport_mbox_file: '%env(TYPO3_PATH_COMPOSER_ROOT)%/log/mails.log'
    defaultMailAddress: 'admin@example.com'
    defaultMailFromName: 'John Doe'
    transport_sendmail_command: '/usr/sbin/sendmail -t -i '