SYS:
    devIPmask: '*'
    displayErrors: false
    enableDeprecationLog: false,
    exceptionalErrors: 0
    sqlDebug: false
    systemLogLevel: 0
    sitename: 'TYPO3 Site'
    trustedHostsPattern: '.*'