DB:
    Connections:
        Default:
            dbname: '%env(TYPO3_INSTALL_DB_NAME)%'
            driver: mysqli
            host: localhost
            username: '%env(TYPO3_INSTALL_DB_USER)%'
            password: '%env(TYPO3_INSTALL_DB_PASSWORD)%'
            port: 3306
            socket: ''
            charset: utf8
