imports:
    - { resource: config.yml }

SYS:
    displayErrors: '1'
    enableDeprecationLog: 'file'
    sqlDebug: '1'
    exceptionalErrors: 28674
MAIL:
    transport: 'mbox'
BE:
    debug: 'true'
FE:
    debug: 'true'